config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :projects,
    :collection => {:tags => :get,
                    :valid_directory => :get,
                    :validate => :get},
    :member => {:features => :get,
                :import_all => :get,
                :import_feature => :get,
                :import => :get}

  map.resources :parking,
    :collection => {:tickets => :get,
                    :unique_resource_name => :get,
                    :import => :post}
  
  map.resources :resources
  
  map.resources :features,
    :collection => {:tags => :get,
                    :sort => :post,
                    :import => :get,
                    :sync => :post,
                    :validate => :get},
    :member => {:stories => :get,
                :source => :get,
                :merge => :get,
                :changes => :get,
                :system_sync => :get,
                :file_merge => :get,
                :system_merge => :get,
                :export => :get}

  map.resources :stories,
    :collection => {:tags => :get,
                    :sort => :post,
                    :validate => :get},
    :member => {:steps => :get,
                :add_step => :post}

  map.resources :steps,
    :collection => {:tags => :get,
                    :sort => :post,
                    :validate_prefix => :get}

  
  map.project_tag 'projects/tag/:tag', :controller => 'projects', :action => 'tag'
  map.feature_tag 'features/tag/:tag', :controller => 'features', :action => 'tag'
  map.story_tag 'stories/tag/:tag', :controller => 'stories', :action => 'tag'

  map.root :controller => "welcome"
  
  map.connect ':controller/:action/:id.:format'
  map.connect ':controller/:action/:id'
end

app/models/feature.rb
require 'pretty_diff'

class Feature < ActiveRecord::Base
	include MyActiveRecordExtensions
  acts_as_taggable

  validates_uniqueness_of   :title, :on => :create
  
  validates_presence_of     :title
  validates_presence_of     :in_order
  validates_presence_of     :as_a
  validates_presence_of     :i_want
  
  validates_associated      :stories, :on => :create

  validates_length_of :title, :minimum => 4, :too_short => :too_short
  validates_length_of :in_order, :minimum => 7, :too_short => :too_short
  validates_length_of :as_a, :minimum => 4, :too_short => :too_short
  validates_length_of :i_want, :minimum => 7, :too_short => :too_short
  
  validate :is_unique?
  validate :valid_feature_path?

  has_many :feature_projects, :order => 'position'
  has_many :projects, :through => :feature_projects
  
  has_many :feature_stories, :order => 'position'
  has_many :stories, :through => :feature_stories

  accepts_nested_attributes_for :stories, :allow_destroy => true
  
  def export
    exported = feature_title
    self.stories.each do |story|
      exported += "#{feature_scenarios story}"
      exported += "#{feature_examples story}"
    end
    exported.rstrip
  end

  def is_diff?
    if not self.path.nil?
      generate_diff
      result = %x{diff -uaw "#{self.path}" "#{RAILS_ROOT}/tmp/#{File.basename(self.path)}.tmp"}
      (result.empty?)? false : true
    end
  end

  def patch
    generate_diff
    %x{diff -uaw "#{self.path}" "#{RAILS_ROOT}/tmp/#{File.basename(self.path)}.tmp"}
  end
  
  def get_source_file
    File.read self.path if not self.path.nil?
  end

  def diff
    generate_diff
    result = %x{diff -uaw "#{RAILS_ROOT}/tmp/#{File.basename(self.path)}.tmp" "#{self.path}"}
    PrettyDiff::Diff.new(result)
  end
  
  def diff_reverse
    generate_diff
    result = %x{diff -uaw "#{self.path}" "#{RAILS_ROOT}/tmp/#{File.basename(self.path)}.tmp"}
    PrettyDiff::Diff.new(result)
  end
  
  def self.imports_found project_path
    found = []
    feature_files = File.join("#{project_path}", "features", "**", "*.feature")
    Dir.glob(feature_files).each { |file| found << FeatureFile.new(file).export if Feature.find_by_path(file).nil? }
    found
  end

  def sync(dry_run = true)
    if self.patch.nil? or self.patch.empty?
      false
    else
      (run_patch(dry_run).include? 'patching file')? true : false
    end
  end

  def sync_system
    self.stories.destroy_all
    feature = FeatureFile.new(self.path).export
    self.stories = feature.stories
    self.update_attributes(feature.attributes)
  end
  
  protected
    def run_patch dry_run
      File.open("#{RAILS_ROOT}/tmp/#{File.basename(self.path)}.patch", 'w') { |f| f.write(self.patch) }
      if dry_run
        %x{patch --dry-run -p1 "#{self.path}" -i "#{RAILS_ROOT}/tmp/#{File.basename(self.path)}.patch"}
      else
        %x{patch -p1 "#{self.path}" -i "#{RAILS_ROOT}/tmp/#{File.basename(self.path)}.patch"}
      end
    end
    
  private
    def generate_diff
      FileUtils.touch("#{RAILS_ROOT}/tmp/#{File.basename(self.path)}.tmp")
      file = File.new("#{RAILS_ROOT}/tmp/#{File.basename(self.path)}.tmp", 'w')
      file.write(self.export)
      file.close  
    end

    def valid_feature_path?
      if not self.path.nil?
        errors.add(:path, "Must be a valid feature location on your system.") if not File.file? self.path
      end
    end
    
    def is_unique?
      Feature.find_by_title self.title == nil
    end
    
    def feature_scenarios story
      result = (story.example.blank?)? "\n  Scenario:" : "\n  Scenario Outline:"
      result += " #{story.scenario}\n#{story_titles story}"unless story.steps.blank?
    end

    def feature_examples story
      if not story.example.nil?
        result = "\n\t\tExamples: #{story.example.heading.lstrip}\n"
        story.example.actions.each { |action| result += "\t\t| #{action.title}" }
        result += " |\n"
        story.example.actions.first.items.each_with_index do |item, index|
          story.example.actions.each do |action|
            result += "\t\t| #{action.items[index].title}"
          end
          result += " |\n"
        end
        result
      end
    end

    def story_titles story
      titles = ""
			last_step = nil
      story.steps.each do |step|
        titles += "#{step.formatted(last_step)}"
        last_step = step
      end
      titles
    end
    
    def feature_title
      head = "Feature: #{title.lstrip}\n\  In order #{in_order.lstrip}\n"
      head += "\  As #{as_a.lstrip}\n\  I want #{i_want.lstrip}\n"
    end
end

app/views/common/forms/_feature_import.html.erb
<% content_for :js_head do %>
  <%= javascript_include_tag "jquery.egrep", "jquery.examples.table" %>
<% end %>

<h3>Feature: <%=h file[:file].sub(/\.feature/,"").gsub(/_/,' ') %></h3>
<%- form_for file[:feature], :url => sync_features_path, :html => {:id => "new_feature",:class => "new_feature hidden", :method => :post} do |f|%>
  <fieldset class="ui-tabs ui-widget ui-widget-content ui-corner-all">
    <%= hidden_field_tag :commit, 'Import' %>
    <%= hidden_field_tag :current_project_id, current_project.id %>
    <%= f.hidden_field :title %>
    <%= f.hidden_field :in_order %>
    <%= f.hidden_field :as_a %>
    <%= f.hidden_field :i_want %>
    <%= f.hidden_field :path %>
    <p id="title"><%=h file[:feature].title%></p>
    <p>
        In order <%=h file[:feature].in_order %><br />
        As <%=h file[:feature].as_a %><br />
        I want <%=h file[:feature].i_want %>
    </p>
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list %><br/>
    <% if !Project.all.empty? %>
      <p>
      <% for project in Project.find :all %>
        <%= check_box_tag "feature[project_ids][]", project.id, feature.projects.include?(project), {:id=>"feature_project_id_#{project.id}"} %>
        <%=h project.title%><br/>
      <% end %>
      </p>

      <% f.fields_for :stories, {:class => 'hidden'} do |stories_f| -%>
        <%= stories_f.hidden_field :scenario %>
        <%= render :partial => '/common/forms/story_steps', :locals => { :f => stories_f } %>
        <%= render :partial => '/common/forms/story_examples', :locals => { :f => stories_f } %>
      <% end -%>
    <% end %>
    <br />
    <% if has_duplicate_feature_name?(file[:feature].path, @imported) %>
    <p id="error">Feature already exists in <%= has_duplicate_feature_name?(file[:feature].path, @imported) %></p>
    <% end %>
    <% if invalid_import? file[:feature] %>
      <p id="error">Invalid feature</p>
    <% elsif has_duplicate_feature? file[:file], @imported %>
      <p id="error">Feature has duplicate scenario</p>    
    <% elsif has_no_stories? file[:feature] %>
      <p id="error">No Scenario's found</p>
    <% else %>
      <button type="submit" class="button positive ui-state-default ui-corner-all ui-button-text"><%= "Import #{file[:file].sub(/\.feature/,"").gsub(/_/," ")}" %></button>
    <% end %>
  </fieldset>
<% end %>

app/views/common/forms/_story_examples.html.erb
<% unless f.object.new_record? %>
	<% f.fields_for :example do |example_f| -%>
	  <%= example_f.hidden_field :heading -%>

	  <% example_f.fields_for :actions do |action_f| -%>
	  <%= action_f.hidden_field :title -%>

	    <% action_f.fields_for :items do |item_f| -%>
	        <%= item_f.hidden_field :title -%>
	    <% end %>

	  <% end -%>
	<% end -%>
<% end %>

app/views/common/forms/_story_steps.html.erb
<% f.fields_for :steps do |step_f| -%>
  <%= step_f.hidden_field :title -%>
<% end -%>